name: Docker Image CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set variables
        id: vars
        run: |
          echo "repository=${GITHUB_ACTOR}/$(basename ${GITHUB_REPOSITORY})" >> $GITHUB_OUTPUT
      - name: Free up disk space
        run: |
          sudo apt autoremove --purge && sudo apt -y clean
          docker system prune -af --volumes
          sudo swapoff -a
          sudo rm -f /swapfile
          df -h
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/bake-action@v3
        with:
          pull: true
          push: true
          no-cache: true
          files: docker-bake.hcl
