name: Docker Image CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [ buster, buster-slim ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Free up disk space
        run: |
          sudo apt autoremove --purge && sudo apt -y clean
          docker system prune -af --volumes
          sudo swapoff -a
          sudo rm -f /swapfile
          df -h
      - name: Build the Docker image
        env:
          DOCKER_BUILDKIT: 1
          TAG_VERSION: ${{ matrix.variant }}
        working-directory: ${{ matrix.variant }}
        run: |
          docker build \
          --pull \
          --no-cache \
          --file Dockerfile \
          --tag chinayin/debian:${TAG_VERSION} \
          .
      - name: Push image to Docker hub
        if: success()
        env:
          TAG_VERSION: ${{ matrix.variant }}
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
          docker push chinayin/debian:${TAG_VERSION}
          docker logout
