name: Docker Image CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [ buster, buster-slim ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set variables
        id: vars
        run: |
          echo ::set-output name=repository::${GITHUB_ACTOR}/$(echo basename ${GITHUB_REPOSITORY})
          echo ::set-output name=tag::${{ matrix.variant }}
      - name: Free up disk space
        run: |
          sudo apt autoremove --purge && sudo apt -y clean
          docker system prune -af --volumes
          sudo swapoff -a
          sudo rm -f /swapfile
          df -h
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.variant }}
          pull: true
          push: true
          no-cache: true
          tags: |
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.tag }}
